name: Build
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"
            - name: Install Bazel
              run: |
                  sudo apt-get install -y apt-transport-https curl gnupg
                  curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
                  sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
                  echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
                  sudo apt-get update
                  sudo apt-get install -y bazel
            - name: Build All
              run: bazel build robot --platforms=@bazelrio//platforms/roborio
